In [18]:
import pandas as pd
import sqlite3

In [30]:
data=pd.read_excel('test.xlsx')

In [31]:
data

,sr,father full name,C_HOUSE_NO,voter name,AC_NO,PART_NO,SLNOINPART,SECTION_NO,EPIC_NO,GENDER,...,RLN_FM_NM_V1,RLN_L_NM_V1,C_HOUSE_NO_V1,MOBILE_NO,Unnamed: 18,Unnamed: 19,Unqiue,length_address,length_name,family group
0,0,Balakrushna ...,996,Prabhavati Balakrushna Bhise ...,202,146,482,2,TML7633142,F,...,बाळकृष्ण ...,भिसे,996,NaN,NaN,NaN,202146TML7633142Prabhavati BalakrushnaBhise ...,10,2,0
1,1,Dilip ...,208,Radha Dilip ...,202,299,469,1,TML1568336,F,...,राधा दिलीप ...,टेकवडे _x0000_,208,NaN,NaN,NaN,202299TML1568336 Radha Dilip ...,10,2,1
2,2,Pandurang ...,2151,Ramchandra Pandurang ...,202,358,227,1,JGM0661900,M,...,चंद्र पांडुरंग ...,भुजबळ _x0000_,2151,NaN,NaN,NaN,202358JGM0661900 Ramchandra Pandurang ...,10,2,2
3,3,Anandrao ...,463,KhushalChand Anandrao ...,202,376,287,3,JGM2304483,M,...,चांद आनंदराव ...,यादव _x0000_,463,NaN,NaN,NaN,202376JGM2304483 KhushalChand Anandrao ...,10,2,3
4,4,Ayub ...,257 1,Zaved Ayub ...,202,273,56,1,TML1857788,M,...,मुजावर आयुब ...,_x0000_,257-1,NaN,NaN,NaN,202273TML1857788 Zaved Ayub ...,10,2,4
5,5,Baba Shinde,226-11,Viraj Baba Shinde,202,387,678,3,TML7591563,M,...,बाबा,शिंदे,226-11,NaN,NaN,NaN,202387TML7591563Viraj BabaShinde BabaShindeM27,6,2,5
6,6,Baban ...,227k,Aruna Baban ...,202,287,726,6,JGM2484897,F,...,महादेव ...,भोराडे _x0000_,227क,NaN,NaN,NaN,202287JGM2484897 Aruna Baban ...,10,2,6
7,7,Dagdu ...,22,Mahadev Dagdu ...,202,55,336,1,TML8155764,M,...,अशोक दगडू ...,पवार _x0000_,221,NaN,NaN,NaN,20255TML8155764Mahadev Dagdu ...,10,2,7
8,8,Dattatray ...,Tel.So.,Anuradha Dattatray ...,202,22,130,1,DFF0703884,F,...,अनुराधा दत्ताञय ...,लोंढे _x0000_,-,9.595687e+09,NaN,NaN,20222DFF0703884 Anuradha Dattatray ...,10,2,8
9,9,Dattatray ...,100,Shankar Dattatray Memane,202,375,252,1,TML7667983,M,...,दत्तात्रय ...,मेमाणे,100,NaN,NaN,NaN,202375TML7667983Shankar DattatrayMemane ...,10,2,9
10,10,Dilip ...,Dattavihar,Supriya Dilip ...,202,21,821,1,DFF0717629,F,...,सुप्रिया दिलीप ...,भोसले _x0000_,दत्तविहार,NaN,NaN,NaN,20221DFF0717629 Supriya Dilip ...,10,2,10
11,11,Dilip ...,Dattavihar,Lata Dilip Bhosale,202,21,820,1,TML7601602,F,...,लता दिलीप ...,भोसले,दत्तविहार,NaN,NaN,NaN,20221TML7601602Lata DilipBhosale ...,10,2,11
12,12,Dnynoba ...,299,Mahesh Dnynoba ...,202,193,951,3,TML4643797,M,...,ज्ञानोबा ...,कोरडे _x0000_,299,NaN,NaN,NaN,202193TML4643797 Mahesh Dnynoba ...,10,2,12
13,13,Dnynoba ...,299,Ranjana Dnynoba ...,202,193,948,3,JGM0134825,F,...,ज्ञानोबा ...,कोरडे _x0000_,299,NaN,NaN,NaN,202193JGM0134825 Ranjana Dnynoba ...,10,2,12
14,14,Dnynoba ...,299,Sanjay Dnynoba ...,202,193,949,3,JGM1677699,M,...,ज्ञानदेव ...,कोरडे _x0000_,299,NaN,NaN,NaN,202193JGM1677699 Sanjay Dnynoba ...,10,2,12
15,15,Dnynoba ...,299,Sarika Dnynoba ...,202,193,950,3,JGM1677723,F,...,ज्ञानोबा ...,कोरडे _x0000_,299,NaN,NaN,NaN,202193JGM1677723 Sarika Dnynoba ...,10,2,12
16,16,Ganesh ...,Bhakaraina,Savita Ganesh ...,202,139,827,4,TML1655067,F,...,गणपत ...,शिंदे _x0000_,भकराईनगर,NaN,NaN,NaN,202139TML1655067 Savita Ganesh ...,10,2,13
17,17,Govind ...,660,Dattatray Govind ...,202,373,235,1,TML7201544,M,...,गोविंद ...,गायकवाड _x0000_,660,NaN,NaN,NaN,202373TML7201544 Dattatray Govind ...,10,2,14
18,18,Gulaammoula ...,Gaonthan,Mohammad Shahid Gulaammoula ...,202,165,508,1,TML4649133,M,...,गुलाममोैला ...,शेख _x0000_,गावठाण,NaN,NaN,NaN,202165TML4649133 Mohammad Shahid Gulaamm...,10,2,15
19,19,Gulab ...,52 11,Suman Gulab ...,202,398,888,3,JGM2183085,F,...,सुमन गुलाब ...,कुचेकर _x0000_,52-11,NaN,NaN,NaN,202398JGM2183085 Suman Gulab ...,10,2,16
20,20,Jaganth ...,102,Shankar Jaganth ...,202,389,176,1,JGM0392936,M,...,जगताप ...,धुमाळ _x0000_,102,NaN,NaN,NaN,202389JGM0392936 Shankar Jaganth ...,10,2,17
21,21,Jaysing ...,170,Nitin Jaysing ...,202,375,381,1,TML7202625,M,...,जयसिंग ...,यादव _x0000_,170,NaN,NaN,NaN,202375TML7202625 Nitin Jaysing ...,10,2,18
22,22,Keru ...,Sarode Nag,Narayan Keru ...,202,116,608,2,GQN0998237,M,...,...,शिंदे _x0000_,सरोदे नगर,NaN,NaN,NaN,202116GQN0998237 Narayan Keru ...,10,2,19
23,23,Mahadev ...,391,Madhuri Mahadev ...,202,346,775,3,JGM0046821,F,...,विष्णु ...,करवंदे _x0000_,391,NaN,NaN,NaN,202346JGM0046821 Madhuri Mahadev ...,10,2,20
24,24,Mariyo ...,Satyapuram,Monti Mariyo ...,202,125,307,1,TML4553574,M,...,...,मस्करनीहास _x0000_,सत्यपुरम,NaN,NaN,NaN,202125TML4553574 Monti Mariyo ...,10,2,21
25,25,Mubaraq Ahmad ...,114 3,Gulame Mustafa Mubaraq ...,202,398,1085,4,JGM2186138,M,...,मुस्तफा मुबारक ...,आतार _x0000_,114-3,NaN,NaN,NaN,202398JGM2186138 Gulame Mustafa Mubaraq ...,10,3,22
26,26,Narayan ...,573,Ankush Narayan ...,202,373,524,3,TML7201676,M,...,नारायण ...,साळुंके _x0000_,573,NaN,NaN,NaN,202373TML7201676 Ankush Narayan ...,10,2,23
27,27,Narsinghram ...,Dattanagar,Viramaram Narsinghram ...,202,21,797,1,DFF0713990,M,...,विरमाराम नरसिंगराम ...,सुतार _x0000_,दत्तनगर,NaN,NaN,NaN,20221DFF0713990 Viramaram Narsinghram ...,10,2,24
28,28,Nivurutti ...,64,Parvati Nivurutti ...,202,59,461,1,GQN1238179,F,...,निवृत्ती ...,खोपडे _x0000_,64,NaN,NaN,NaN,20259GQN1238179 Parvati Nivurutti ...,10,2,25
29,29,Prahlad ...,Pawar,Kasturabai Prahlad ...,202,151,962,4,TML7156656,F,...,प्रल्हाद ...,इसाळे _x0000_,पावर,NaN,NaN,NaN,202151TML7156656 Kasturabai Prahlad ...,10,2,26
30,30,Pratap Bajirao Rananaware,At/Post-Rakh,Priyanka Prataprao Rananaware,202,340,705,2,TML8611543,F,...,प्रताप बाजीराव,रणनवरे,एट/पोस्त-रख,8.135706e+09,NaN,NaN,202340TML8611543 Priyanka Prataprao Rananaware...,12,3,27

In [23]:
mini_data=data.to_dict('list')

In [24]:
nan=''
mini_data

{'sr': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30],
 'father full name': ['  Balakrushna                                      Bhise                         ',
  '  Dilip                                                           Tekwade                       ',
  '  Pandurang                                                       Bhujbal                       ',
  ' Anandrao                                                         Yadav                         ',
  ' Ayub                                                             Muzawar                       ',
  ' Baba Shinde',
  ' Baban                                                            Bhorade                       ',
  ' Dagdu                                                            Pawar                         ',
  ' Dattatray                                                        Londhe                        ',
  ' Dattatray                                         Memane                        ',
  ' Dilip                                                            Bhosle                        ',
  ' Dilip                                             Bhosale                       ',
  ' Dnynoba                                                          Korde                         ',
  ' Dnynoba                                                          Korde                         ',
  ' Dnynoba                                                          Korde                         ',
  ' Dnynoba                                                          Korde                         ',
  ' Ganesh                                                           Shinde                        ',
  ' Govind                                                           Gayakwad                      ',
  ' Gulaammoula                                                      Shaikh                        ',
  ' Gulab                                                            Kuchekar                      ',
  ' Jaganth                                                          Dhumal                        ',
  ' Jaysing                                                          Yadav                         ',
  ' Keru                                                             Shinde                        ',
  ' Mahadev                                                          Karvande                      ',
  ' Mariyo                                                           Maskaranihas                  ',
  ' Mubaraq Ahmad                                                    Atar                          ',
  ' Narayan                                                          Salunke                       ',
  ' Narsinghram                                                      Sutar                         ',
  ' Nivurutti                                                        Khopade                       ',
  ' Prahlad                                                          Isale                         ',
  ' Pratap Bajirao  Rananaware '],
 'C_HOUSE_NO': ['996       ',
  '208       ',
  '2151      ',
  '463       ',
  '257 1     ',
  '226-11',
  '227k      ',
  '22        ',
  'Tel.So.   ',
  '100       ',
  'Dattavihar',
  'Dattavihar',
  '299       ',
  '299       ',
  '299       ',
  '299       ',
  'Bhakaraina',
  '660       ',
  'Gaonthan  ',
  '52 11     ',
  '102       ',
  '170       ',
  'Sarode Nag',
  '391       ',
  'Satyapuram',
  '114 3     ',
  '573       ',
  'Dattanagar',
  '64        ',
  'Pawar     ',
  'At/Post-Rakh'],
 'voter name': ['Prabhavati Balakrushna Bhise                         ',
  'Radha Dilip                                                       Tekwade                       ',
  'Ramchandra Pandurang                                              Bhujbal                       ',
  'KhushalChand Anandrao                                             Yadav                         ',
  ' Zaved Ayub                                                       Muzawar                       ',
  'Viraj Baba Shinde',
  'Aruna Baban                                                       Bhorade                       ',
  'Mahadev Dagdu                                                     Pawar                         ',
  'Anuradha  Dattatray                                               Londhe                        ',
  'Shankar Dattatray Memane                        ',
  ' Supriya Dilip                                                    Bhosle                        ',
  'Lata Dilip Bhosale                       ',
  'Mahesh  Dnynoba                                                   Korde                         ',
  'Ranjana Dnynoba                                                   Korde                         ',
  'Sanjay  Dnynoba                                                   Korde                         ',
  'Sarika  Dnynoba                                                   Korde                         ',
  'Savita Ganesh                                                     Shinde                        ',
  'Dattatray Govind                                                  Gayakwad                      ',
  'Mohammad Shahid Gulaammoula                                       Shaikh                        ',
  'Suman Gulab                                                       Kuchekar                      ',
  'Shankar Jaganth                                                   Dhumal                        ',
  'Nitin Jaysing                                                     Yadav                         ',
  'Narayan Keru                                                      Shinde                        ',
  'Madhuri Mahadev                                                   Karvande                      ',
  'Monti  Mariyo                                                     Maskaranihas                  ',
  'Gulame Mustafa Mubaraq                                            Atar                          ',
  'Ankush Narayan                                                    Salunke                       ',
  ' Viramaram Narsinghram                                            Sutar                         ',
  'Parvati Nivurutti                                                 Khopade                       ',
  'Kasturabai  Prahlad                                               Isale                         ',
  ' Priyanka Prataprao  Rananaware '],
 'AC_NO': [202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202,
  202],
 'PART_NO': [146,
  299,
  358,
  376,
  273,
  387,
  287,
  55,
  22,
  375,
  21,
  21,
  193,
  193,
  193,
  193,
  139,
  373,
  165,
  398,
  389,
  375,
  116,
  346,
  125,
  398,
  373,
  21,
  59,
  151,
  340],
 'SLNOINPART': [482,
  469,
  227,
  287,
  56,
  678,
  726,
  336,
  130,
  252,
  821,
  820,
  951,
  948,
  949,
  950,
  827,
  235,
  508,
  888,
  176,
  381,
  608,
  775,
  307,
  1085,
  524,
  797,
  461,
  962,
  705],
 'SECTION_NO': [2,
  1,
  1,
  3,
  1,
  3,
  6,
  1,
  1,
  1,
  1,
  1,
  3,
  3,
  3,
  3,
  4,
  1,
  1,
  3,
  1,
  1,
  2,
  3,
  1,
  4,
  3,
  1,
  1,
  4,
  2],
 'EPIC_NO': ['TML7633142',
  'TML1568336       ',
  'JGM0661900       ',
  'JGM2304483       ',
  'TML1857788       ',
  'TML7591563',
  'JGM2484897       ',
  'TML8155764',
  'DFF0703884       ',
  'TML7667983',
  'DFF0717629       ',
  'TML7601602',
  'TML4643797       ',
  'JGM0134825       ',
  'JGM1677699       ',
  'JGM1677723       ',
  'TML1655067       ',
  'TML7201544       ',
  'TML4649133       ',
  'JGM2183085       ',
  'JGM0392936       ',
  'TML7202625       ',
  'GQN0998237       ',
  'JGM0046821       ',
  'TML4553574       ',
  'JGM2186138       ',
  'TML7201676       ',
  'DFF0713990       ',
  'GQN1238179       ',
  'TML7156656       ',
  'TML8611543'],
 'GENDER': ['F',
  'F',
  'M',
  'M',
  'M',
  'M',
  'F',
  'M',
  'F',
  'M',
  'F',
  'F',
  'M',
  'F',
  'M',
  'F',
  'F',
  'M',
  'M',
  'F',
  'M',
  'M',
  'M',
  'F',
  'M',
  'M',
  'M',
  'M',
  'F',
  'F',
  'F'],
 'AGE': [65,
  42,
  38,
  58,
  40,
  27,
  60,
  39,
  42,
  40,
  40,
  57,
  33,
  54,
  41,
  39,
  49,
  43,
  46,
  80,
  46,
  39,
  78,
  44,
  70,
  41,
  48,
  55,
  67,
  60,
  24],
 'FM_NAME_EN': ['Prabhavati Balakrushna',
  'Radha Dilip                                                      ',
  'Ramchandra Pandurang                                             ',
  'KhushalChand Anandrao                                            ',
  ' Zaved Ayub                                                      ',
  'Viraj Baba',
  'Aruna Baban                                                      ',
  'Mahadev Dagdu                                                    ',
  'Anuradha  Dattatray                                              ',
  'Shankar Dattatray',
  ' Supriya Dilip                                                   ',
  'Lata Dilip',
  'Mahesh  Dnynoba                                                  ',
  'Ranjana Dnynoba                                                  ',
  'Sanjay  Dnynoba                                                  ',
  'Sarika  Dnynoba                                                  ',
  'Savita Ganesh                                                    ',
  'Dattatray Govind                                                 ',
  'Mohammad Shahid Gulaammoula                                      ',
  'Suman Gulab                                                      ',
  'Shankar Jaganth                                                  ',
  'Nitin Jaysing                                                    ',
  'Narayan Keru                                                     ',
  'Madhuri Mahadev                                                  ',
  'Monti  Mariyo                                                    ',
  'Gulame Mustafa Mubaraq                                           ',
  'Ankush Narayan                                                   ',
  ' Viramaram Narsinghram                                           ',
  'Parvati Nivurutti                                                ',
  'Kasturabai  Prahlad                                              ',
  ' Priyanka Prataprao '],
 'LASTNAME_EN': ['Bhise                         ',
  'Tekwade                       ',
  'Bhujbal                       ',
  'Yadav                         ',
  'Muzawar                       ',
  'Shinde',
  'Bhorade                       ',
  'Pawar                         ',
  'Londhe                        ',
  'Memane                        ',
  'Bhosle                        ',
  'Bhosale                       ',
  'Korde                         ',
  'Korde                         ',
  'Korde                         ',
  'Korde                         ',
  'Shinde                        ',
  'Gayakwad                      ',
  'Shaikh                        ',
  'Kuchekar                      ',
  'Dhumal                        ',
  'Yadav                         ',
  'Shinde                        ',
  'Karvande                      ',
  'Maskaranihas                  ',
  'Atar                          ',
  'Salunke                       ',
  'Sutar                         ',
  'Khopade                       ',
  'Isale                         ',
  'Rananaware '],
 'RLN_FM_NM_EN': ['  Balakrushna                                     ',
  '  Dilip                                                          ',
  '  Pandurang                                                      ',
  ' Anandrao                                                        ',
  ' Ayub                                                            ',
  ' Baba',
  ' Baban                                                           ',
  ' Dagdu                                                           ',
  ' Dattatray                                                       ',
  ' Dattatray                                        ',
  ' Dilip                                                           ',
  ' Dilip                                            ',
  ' Dnynoba                                                         ',
  ' Dnynoba                                                         ',
  ' Dnynoba                                                         ',
  ' Dnynoba                                                         ',
  ' Ganesh                                                          ',
  ' Govind                                                          ',
  ' Gulaammoula                                                     ',
  ' Gulab                                                           ',
  ' Jaganth                                                         ',
  ' Jaysing                                                         ',
  ' Keru                                                            ',
  ' Mahadev                                                         ',
  ' Mariyo                                                          ',
  ' Mubaraq Ahmad                                                   ',
  ' Narayan                                                         ',
  ' Narsinghram                                                     ',
  ' Nivurutti                                                       ',
  ' Prahlad                                                         ',
  ' Pratap Bajirao '],
 'RLN_L_NM_EN': ['Bhise                         ',
  'Tekwade                       ',
  'Bhujbal                       ',
  'Yadav                         ',
  'Muzawar                       ',
  'Shinde',
  'Bhorade                       ',
  'Pawar                         ',
  'Londhe                        ',
  'Memane                        ',
  'Bhosle                        ',
  'Bhosale                       ',
  'Korde                         ',
  'Korde                         ',
  'Korde                         ',
  'Korde                         ',
  'Shinde                        ',
  'Gayakwad                      ',
  'Shaikh                        ',
  'Kuchekar                      ',
  'Dhumal                        ',
  'Yadav                         ',
  'Shinde                        ',
  'Karvande                      ',
  'Maskaranihas                  ',
  'Atar                          ',
  'Salunke                       ',
  'Sutar                         ',
  'Khopade                       ',
  'Isale                         ',
  'Rananaware '],
 'FM_NAME_V1': ['प्रभावती बाळकृष्ण',
  'राधा दिलीप                                                       _x0000_',
  'राम चंद्र पांडुरंग                                               _x0000_',
  'खुशाल चांद आनंदराव                                               _x0000_',
  'मुजावर जावेद आयु                                                 _x0000_',
  'विराज बाबा',
  'अरुणा बबन महादेव                                                 _x0000_',
  'महादेव दगडू                                                      _x0000_',
  'अनुराधा कोंडीबा                                                  _x0000_',
  'शंकर दत्तात्रय',
  'भोसले सुप्रिया दिलीप                                             _x0000_',
  'े लता दिलीप',
  'महेश ज्ञानोबा                                                    _x0000_',
  'रंजना ज्ञानोबा                                                   _x0000_',
  'संजय ज्ञानदेव                                                    _x0000_',
  'सारीका ज्ञानोबा                                                  _x0000_',
  'सविता गणपत                                                       _x0000_',
  'दत्तात्रय गोविंद                                                 _x0000_',
  '  मोहम्मदशहिद गुलाममोैला                                         _x0000_',
  'सुमन गुलाब                                                       _x0000_',
  'शंकर जगताप                                                       _x0000_',
  'नितीन जयसिंग                                                     _x0000_',
  'नारायण                                                           _x0000_',
  'माधुरी महादेव विष्णु                                             _x0000_',
  'मॉन्टी                                                           _x0000_',
  'गुलामे मुस्तफा मुबारक                                            _x0000_',
  'अंकुश नारायण                                                     _x0000_',
  'सुतार विरमाराम नरसिंगराम                                         _x0000_',
  'पार्वताबाई निवृत्ती                                              _x0000_',
  'कस्तुराबाई प्रल्हाद                                              _x0000_',
  ' प्रियंका प्रतापराव '],
 'LASTNAME_V1': ['भिसे                          ',
  'टेकवडे                        _x0000_',
  'भुजबळ                         _x0000_',
  'यादव                          _x0000_',
  '                              _x0000_',
  'शिंदे',
  'भोराडे                        _x0000_',
  'पवार                          _x0000_',
  'लोंढे                         _x0000_',
  'मेमाणे                        ',
  'भोसले                         _x0000_',
  'भोसले                         ',
  'कोरडे                         _x0000_',
  'कोरडे                         _x0000_',
  'कोरडे                         _x0000_',
  'कोरडे                         _x0000_',
  'शिंदे                         _x0000_',
  'गायकवाड                       _x0000_',
  'शेख                           _x0000_',
  'कुचेकर                        _x0000_',
  'धुमाळ                         _x0000_',
  'यादव                          _x0000_',
  'शिंदे                         _x0000_',
  'करवंदे                        _x0000_',
  'मस्करनीहास                    _x0000_',
  'आतार                          _x0000_',
  'साळुंके                       _x0000_',
  'सुतार                         _x0000_',
  'खोपडे                         _x0000_',
  'इसाळे                         _x0000_',
  'रणनवरे '],
 'RLN_FM_NM_V1': ['बाळकृष्ण                                                               ',
  'राधा दिलीप                                                       _x0000_',
  'चंद्र पांडुरंग                                                   _x0000_',
  'चांद आनंदराव                                                     _x0000_',
  'मुजावर आयुब                                                      _x0000_',
  'बाबा',
  'महादेव                                                           _x0000_',
  'अशोक दगडू                                                        _x0000_',
  'अनुराधा दत्ताञय                                                  _x0000_',
  ' दत्तात्रय                                                         ',
  'सुप्रिया दिलीप                                                   _x0000_',
  'लता दिलीप                                                        ',
  'ज्ञानोबा                                                         _x0000_',
  'ज्ञानोबा                                                         _x0000_',
  'ज्ञानदेव                                                         _x0000_',
  'ज्ञानोबा                                                         _x0000_',
  'गणपत                                                             _x0000_',
  'गोविंद                                                           _x0000_',
  'गुलाममोैला                                                       _x0000_',
  'सुमन गुलाब                                                       _x0000_',
  'जगताप                                                            _x0000_',
  'जयसिंग                                                           _x0000_',
  '                                                                 _x0000_',
  'विष्णु                                                           _x0000_',

In [13]:
conn = sqlite3.connect('test_database') 
c = conn.cursor()

c.execute('''
          CREATE TABLE IF NOT EXISTS products
          ([product_id] INTEGER PRIMARY KEY, [product_name] TEXT, [price] INTEGER)
          ''')
          
c.execute('''
          INSERT INTO products (product_id, product_name, price)

                VALUES
                (1,'Computer',800),
                (2,'Printer',200),
                (3,'Tablet',300),
                (4,'Desk',450),
                (5,'Chair',150)
          ''')                     

conn.commit()

In [14]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('test_database') 
          
sql_query = pd.read_sql_query ('''
                               SELECT
                               *
                               FROM products
                               ''', conn)

df = pd.DataFrame(sql_query, columns = ['product_id', 'product_name', 'price'])
print (df)

   product_id product_name  price
0           1     Computer    800
1           2      Printer    200
2           3       Tablet    300
3           4         Desk    450
4           5        Chair    150

In [15]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('test_database') 
c = conn.cursor()
                 
c.execute('''
          SELECT
          *
          FROM products
          ''')

df = pd.DataFrame(c.fetchall(), columns = ['product_id', 'product_name', 'price'])
print (df)

   product_id product_name  price
0           1     Computer    800
1           2      Printer    200
2           3       Tablet    300
3           4         Desk    450
4           5        Chair    150

In [16]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('test_database') 
c = conn.cursor()
                 
c.execute('''
          SELECT
          *
          FROM products
          ''')

df = pd.DataFrame(c.fetchall(), columns = ['product_id', 'product_name', 'price'])

max_price = df['price'].max()
print (max_price)

800

In [18]:
cnx = sqlite3.connect(':memory:')

In [23]:
data.to_sql(name='price3', con=cnx, index=False)

32

In [24]:
p2 = pd.read_sql('select * from price3', cnx)

In [25]:
p2

,sr,father full name,C_HOUSE_NO,voter name,AC_NO,PART_NO,SLNOINPART,SECTION_NO,EPIC_NO,GENDER,...,C_HOUSE_NO_V1,MOBILE_NO,Unnamed: 18,Unnamed: 19,Unqiue,length_address,length_name,family group,mobile_available,Age_Between
0,0,Balakrushna ...,996,Prabhavati Balakrushna Bhise ...,202.0,146,482.0,2.0,TML7633142,F,...,996,NaN,None,None,202146TML7633142Prabhavati BalakrushnaBhise ...,10.0,2.0,0,None,21 to 25
1,1,Dilip ...,208,Radha Dilip ...,202.0,299,469.0,1.0,TML1568336,F,...,208,NaN,None,None,202299TML1568336 Radha Dilip ...,10.0,2.0,1,None,21 to 25
2,2,Pandurang ...,2151,Ramchandra Pandurang ...,202.0,358,227.0,1.0,JGM0661900,M,...,2151,NaN,None,None,202358JGM0661900 Ramchandra Pandurang ...,10.0,2.0,2,None,21 to 25
3,3,Anandrao ...,463,KhushalChand Anandrao ...,202.0,376,287.0,3.0,JGM2304483,M,...,463,NaN,None,None,202376JGM2304483 KhushalChand Anandrao ...,10.0,2.0,3,None,21 to 25
4,4,Ayub ...,257 1,Zaved Ayub ...,202.0,273,56.0,1.0,TML1857788,M,...,257-1,NaN,None,None,202273TML1857788 Zaved Ayub ...,10.0,2.0,4,None,21 to 25
5,5,Baba Shinde,226-11,Viraj Baba Shinde,202.0,387,678.0,3.0,TML7591563,M,...,226-11,NaN,None,None,202387TML7591563Viraj BabaShinde BabaShindeM27,6.0,2.0,5,None,21 to 25
6,6,Baban ...,227k,Aruna Baban ...,202.0,287,726.0,6.0,JGM2484897,F,...,227क,NaN,None,None,202287JGM2484897 Aruna Baban ...,10.0,2.0,6,None,21 to 25
7,7,Dagdu ...,22,Mahadev Dagdu ...,202.0,55,336.0,1.0,TML8155764,M,...,221,NaN,None,None,20255TML8155764Mahadev Dagdu ...,10.0,2.0,7,None,21 to 25
8,8,Dattatray ...,Tel.So.,Anuradha Dattatray ...,202.0,22,130.0,1.0,DFF0703884,F,...,-,75521079.0,None,None,20222DFF0703884 Anuradha Dattatray ...,10.0,2.0,8,None,21 to 25
9,9,Dattatray ...,100,Shankar Dattatray Memane,202.0,375,252.0,1.0,TML7667983,M,...,100,NaN,None,None,202375TML7667983Shankar DattatrayMemane ...,10.0,2.0,9,None,21 to 25
10,10,Dilip ...,Dattavihar,Supriya Dilip ...,202.0,21,821.0,1.0,DFF0717629,F,...,दत्तविहार,NaN,None,None,20221DFF0717629 Supriya Dilip ...,10.0,2.0,10,None,21 to 25
11,11,Dilip ...,Dattavihar,Lata Dilip Bhosale,202.0,21,820.0,1.0,TML7601602,F,...,दत्तविहार,NaN,None,None,20221TML7601602Lata DilipBhosale ...,10.0,2.0,11,None,21 to 25
12,12,Dnynoba ...,299,Mahesh Dnynoba ...,202.0,193,951.0,3.0,TML4643797,M,...,299,NaN,None,None,202193TML4643797 Mahesh Dnynoba ...,10.0,2.0,12,None,21 to 25
13,13,Dnynoba ...,299,Ranjana Dnynoba ...,202.0,193,948.0,3.0,JGM0134825,F,...,299,NaN,None,None,202193JGM0134825 Ranjana Dnynoba ...,10.0,2.0,12,None,21 to 25
14,14,Dnynoba ...,299,Sanjay Dnynoba ...,202.0,193,949.0,3.0,JGM1677699,M,...,299,NaN,None,None,202193JGM1677699 Sanjay Dnynoba ...,10.0,2.0,12,None,21 to 25
15,15,Dnynoba ...,299,Sarika Dnynoba ...,202.0,193,950.0,3.0,JGM1677723,F,...,299,NaN,None,None,202193JGM1677723 Sarika Dnynoba ...,10.0,2.0,12,None,21 to 25
16,16,Ganesh ...,Bhakaraina,Savita Ganesh ...,202.0,139,827.0,4.0,TML1655067,F,...,भकराईनगर,NaN,None,None,202139TML1655067 Savita Ganesh ...,10.0,2.0,13,None,21 to 25
17,17,Govind ...,660,Dattatray Govind ...,202.0,373,235.0,1.0,TML7201544,M,...,660,NaN,None,None,202373TML7201544 Dattatray Govind ...,10.0,2.0,14,None,21 to 25
18,18,Gulaammoula ...,Gaonthan,Mohammad Shahid Gulaammoula ...,202.0,165,508.0,1.0,TML4649133,M,...,गावठाण,NaN,None,None,202165TML4649133 Mohammad Shahid Gulaamm...,10.0,2.0,15,None,21 to 25
19,19,Gulab ...,52 11,Suman Gulab ...,202.0,398,888.0,3.0,JGM2183085,F,...,52-11,NaN,None,None,202398JGM2183085 Suman Gulab ...,10.0,2.0,16,None,21 to 25
20,20,Jaganth ...,102,Shankar Jaganth ...,202.0,389,176.0,1.0,JGM0392936,M,...,102,NaN,None,None,202389JGM0392936 Shankar Jaganth ...,10.0,2.0,17,None,21 to 25
21,21,Jaysing ...,170,Nitin Jaysing ...,202.0,375,381.0,1.0,TML7202625,M,...,170,NaN,None,None,202375TML7202625 Nitin Jaysing ...,10.0,2.0,18,None,21 to 25
22,22,Keru ...,Sarode Nag,Narayan Keru ...,202.0,116,608.0,2.0,GQN0998237,M,...,सरोदे नगर,NaN,None,None,202116GQN0998237 Narayan Keru ...,10.0,2.0,19,None,21 to 25
23,23,Mahadev ...,391,Madhuri Mahadev ...,202.0,346,775.0,3.0,JGM0046821,F,...,391,NaN,None,None,202346JGM0046821 Madhuri Mahadev ...,10.0,2.0,20,None,21 to 25
24,24,Mariyo ...,Satyapuram,Monti Mariyo ...,202.0,125,307.0,1.0,TML4553574,M,...,सत्यपुरम,NaN,None,None,202125TML4553574 Monti Mariyo ...,10.0,2.0,21,None,21 to 25
25,25,Mubaraq Ahmad ...,114 3,Gulame Mustafa Mubaraq ...,202.0,398,1085.0,4.0,JGM2186138,M,...,114-3,NaN,None,None,202398JGM2186138 Gulame Mustafa Mubaraq ...,10.0,3.0,22,None,21 to 25
26,26,Narayan ...,573,Ankush Narayan ...,202.0,373,524.0,3.0,TML7201676,M,...,573,NaN,None,None,202373TML7201676 Ankush Narayan ...,10.0,2.0,23,None,21 to 25
27,27,Narsinghram ...,Dattanagar,Viramaram Narsinghram ...,202.0,21,797.0,1.0,DFF0713990,M,...,दत्तनगर,NaN,None,None,20221DFF0713990 Viramaram Narsinghram ...,10.0,2.0,24,None,21 to 25
28,28,Nivurutti ...,64,Parvati Nivurutti ...,202.0,59,461.0,1.0,GQN1238179,F,...,64,NaN,None,None,20259GQN1238179 Parvati Nivurutti ...,10.0,2.0,25,None,21 to 25
29,29,Prahlad ...,Pawar,Kasturabai Prahlad ...,202.0,151,962.0,4.0,TML7156656,F,...,पावर,NaN,None,None,202151TML7156656 Kasturabai Prahlad ...,10.0,2.0,26,None,21 to 25
30,30,Pratap Bajirao Rananaware,At/Post-Rakh,Priyanka Prataprao Rananaware,202.0,340,705.0,2.0,TML8611543,F,...,एट/पोस्त-रख,61133747.0,None,None,202340TML8611543 Priyanka Prataprao Rananaware...,12.0,3.0,27,None,25 to 30
31,31,vinayak rokde,121,vaibhav rokde,NaN,121,NaN,NaN,5161651698,M,...,None,12.0,None,None,None,NaN,NaN,12,None,None

In [2]:
#test

In [25]:
data = pd.read_excel(r"test.xlsx")
    #data = pd.read_excel(r"H:\vaibhav\PycharmProjects\PythonTkinterDashboard-main\test.xlsx")
    #cnx = sqlite3.connect('test_database')
    #data = pd.read_sql('select * from data1', cnx)
data['mobile_available'] = ''
for m in range(len(data['MOBILE_NO'])):
    mobile=str(data.iloc[m,20])
    mobile=mobile.replace('NaN', '').replace(' ', '').replace('_', '').replace('nan', '').replace('+', '')
    data.iloc[m, 20]=mobile
    if len(mobile) == 10 or len(mobile) == 12 or len(mobile) == 13:
        data.iloc[m, 20]=mobile[-12:-2]
        print(len(data.iloc[m, 20]))
        if data.iloc[m, 20] != '':
            data.iloc[m, -1] = 'Available'
            print(data.iloc[m, -1])
    else:
        data.iloc[m, -1] = 'Not_Available'
        print(data.iloc[m, -1])

print(data['MOBILE_NO'])
   
print(data['mobile_available'].value_counts().to_frame())

Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
10
Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
Not_Available
10
Available
0
1
2
3
4
5
6
7
8     9595686859
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30    8135705599
Name: MOBILE_NO, dtype: object
               mobile_available
Not_Available                29
Available                     2

In [26]:
data

,sr,father full name,C_HOUSE_NO,voter name,AC_NO,PART_NO,SLNOINPART,SECTION_NO,EPIC_NO,GENDER,...,RLN_L_NM_V1,C_HOUSE_NO_V1,MOBILE_NO,Unnamed: 18,Unnamed: 19,Unqiue,length_address,length_name,family group,mobile_available
0,0,Balakrushna ...,996,Prabhavati Balakrushna Bhise ...,202,146,482,2,TML7633142,F,...,भिसे,996,,NaN,NaN,202146TML7633142Prabhavati BalakrushnaBhise ...,10,2,0,Not_Available
1,1,Dilip ...,208,Radha Dilip ...,202,299,469,1,TML1568336,F,...,टेकवडे _x0000_,208,,NaN,NaN,202299TML1568336 Radha Dilip ...,10,2,1,Not_Available
2,2,Pandurang ...,2151,Ramchandra Pandurang ...,202,358,227,1,JGM0661900,M,...,भुजबळ _x0000_,2151,,NaN,NaN,202358JGM0661900 Ramchandra Pandurang ...,10,2,2,Not_Available
3,3,Anandrao ...,463,KhushalChand Anandrao ...,202,376,287,3,JGM2304483,M,...,यादव _x0000_,463,,NaN,NaN,202376JGM2304483 KhushalChand Anandrao ...,10,2,3,Not_Available
4,4,Ayub ...,257 1,Zaved Ayub ...,202,273,56,1,TML1857788,M,...,_x0000_,257-1,,NaN,NaN,202273TML1857788 Zaved Ayub ...,10,2,4,Not_Available
5,5,Baba Shinde,226-11,Viraj Baba Shinde,202,387,678,3,TML7591563,M,...,शिंदे,226-11,,NaN,NaN,202387TML7591563Viraj BabaShinde BabaShindeM27,6,2,5,Not_Available
6,6,Baban ...,227k,Aruna Baban ...,202,287,726,6,JGM2484897,F,...,भोराडे _x0000_,227क,,NaN,NaN,202287JGM2484897 Aruna Baban ...,10,2,6,Not_Available
7,7,Dagdu ...,22,Mahadev Dagdu ...,202,55,336,1,TML8155764,M,...,पवार _x0000_,221,,NaN,NaN,20255TML8155764Mahadev Dagdu ...,10,2,7,Not_Available
8,8,Dattatray ...,Tel.So.,Anuradha Dattatray ...,202,22,130,1,DFF0703884,F,...,लोंढे _x0000_,-,9595686859,NaN,NaN,20222DFF0703884 Anuradha Dattatray ...,10,2,8,Available
9,9,Dattatray ...,100,Shankar Dattatray Memane,202,375,252,1,TML7667983,M,...,मेमाणे,100,,NaN,NaN,202375TML7667983Shankar DattatrayMemane ...,10,2,9,Not_Available
10,10,Dilip ...,Dattavihar,Supriya Dilip ...,202,21,821,1,DFF0717629,F,...,भोसले _x0000_,दत्तविहार,,NaN,NaN,20221DFF0717629 Supriya Dilip ...,10,2,10,Not_Available
11,11,Dilip ...,Dattavihar,Lata Dilip Bhosale,202,21,820,1,TML7601602,F,...,भोसले,दत्तविहार,,NaN,NaN,20221TML7601602Lata DilipBhosale ...,10,2,11,Not_Available
12,12,Dnynoba ...,299,Mahesh Dnynoba ...,202,193,951,3,TML4643797,M,...,कोरडे _x0000_,299,,NaN,NaN,202193TML4643797 Mahesh Dnynoba ...,10,2,12,Not_Available
13,13,Dnynoba ...,299,Ranjana Dnynoba ...,202,193,948,3,JGM0134825,F,...,कोरडे _x0000_,299,,NaN,NaN,202193JGM0134825 Ranjana Dnynoba ...,10,2,12,Not_Available
14,14,Dnynoba ...,299,Sanjay Dnynoba ...,202,193,949,3,JGM1677699,M,...,कोरडे _x0000_,299,,NaN,NaN,202193JGM1677699 Sanjay Dnynoba ...,10,2,12,Not_Available
15,15,Dnynoba ...,299,Sarika Dnynoba ...,202,193,950,3,JGM1677723,F,...,कोरडे _x0000_,299,,NaN,NaN,202193JGM1677723 Sarika Dnynoba ...,10,2,12,Not_Available
16,16,Ganesh ...,Bhakaraina,Savita Ganesh ...,202,139,827,4,TML1655067,F,...,शिंदे _x0000_,भकराईनगर,,NaN,NaN,202139TML1655067 Savita Ganesh ...,10,2,13,Not_Available
17,17,Govind ...,660,Dattatray Govind ...,202,373,235,1,TML7201544,M,...,गायकवाड _x0000_,660,,NaN,NaN,202373TML7201544 Dattatray Govind ...,10,2,14,Not_Available
18,18,Gulaammoula ...,Gaonthan,Mohammad Shahid Gulaammoula ...,202,165,508,1,TML4649133,M,...,शेख _x0000_,गावठाण,,NaN,NaN,202165TML4649133 Mohammad Shahid Gulaamm...,10,2,15,Not_Available
19,19,Gulab ...,52 11,Suman Gulab ...,202,398,888,3,JGM2183085,F,...,कुचेकर _x0000_,52-11,,NaN,NaN,202398JGM2183085 Suman Gulab ...,10,2,16,Not_Available
20,20,Jaganth ...,102,Shankar Jaganth ...,202,389,176,1,JGM0392936,M,...,धुमाळ _x0000_,102,,NaN,NaN,202389JGM0392936 Shankar Jaganth ...,10,2,17,Not_Available
21,21,Jaysing ...,170,Nitin Jaysing ...,202,375,381,1,TML7202625,M,...,यादव _x0000_,170,,NaN,NaN,202375TML7202625 Nitin Jaysing ...,10,2,18,Not_Available
22,22,Keru ...,Sarode Nag,Narayan Keru ...,202,116,608,2,GQN0998237,M,...,शिंदे _x0000_,सरोदे नगर,,NaN,NaN,202116GQN0998237 Narayan Keru ...,10,2,19,Not_Available
23,23,Mahadev ...,391,Madhuri Mahadev ...,202,346,775,3,JGM0046821,F,...,करवंदे _x0000_,391,,NaN,NaN,202346JGM0046821 Madhuri Mahadev ...,10,2,20,Not_Available
24,24,Mariyo ...,Satyapuram,Monti Mariyo ...,202,125,307,1,TML4553574,M,...,मस्करनीहास _x0000_,सत्यपुरम,,NaN,NaN,202125TML4553574 Monti Mariyo ...,10,2,21,Not_Available
25,25,Mubaraq Ahmad ...,114 3,Gulame Mustafa Mubaraq ...,202,398,1085,4,JGM2186138,M,...,आतार _x0000_,114-3,,NaN,NaN,202398JGM2186138 Gulame Mustafa Mubaraq ...,10,3,22,Not_Available
26,26,Narayan ...,573,Ankush Narayan ...,202,373,524,3,TML7201676,M,...,साळुंके _x0000_,573,,NaN,NaN,202373TML7201676 Ankush Narayan ...,10,2,23,Not_Available
27,27,Narsinghram ...,Dattanagar,Viramaram Narsinghram ...,202,21,797,1,DFF0713990,M,...,सुतार _x0000_,दत्तनगर,,NaN,NaN,20221DFF0713990 Viramaram Narsinghram ...,10,2,24,Not_Available
28,28,Nivurutti ...,64,Parvati Nivurutti ...,202,59,461,1,GQN1238179,F,...,खोपडे _x0000_,64,,NaN,NaN,20259GQN1238179 Parvati Nivurutti ...,10,2,25,Not_Available
29,29,Prahlad ...,Pawar,Kasturabai Prahlad ...,202,151,962,4,TML7156656,F,...,इसाळे _x0000_,पावर,,NaN,NaN,202151TML7156656 Kasturabai Prahlad ...,10,2,26,Not_Available
30,30,Pratap Bajirao Rananaware,At/Post-Rakh,Priyanka Prataprao Rananaware,202,340,705,2,TML8611543,F,...,रणनवरे,एट/पोस्त-रख,8135705599,NaN,NaN,202340TML8611543 Priyanka Prataprao Rananaware...,12,3,27,Available

In [12]:
data = pd.read_excel(r"test.xlsx")

In [13]:
data.columns

Index(['sr', 'father full name', 'C_HOUSE_NO', 'voter name', 'AC_NO',
       'PART_NO', 'SLNOINPART', 'SECTION_NO', 'EPIC_NO', 'GENDER', 'AGE',
       'FM_NAME_EN', 'LASTNAME_EN', 'RLN_FM_NM_EN', 'RLN_L_NM_EN',
       'FM_NAME_V1', 'LASTNAME_V1', 'RLN_FM_NM_V1', 'RLN_L_NM_V1',
       'C_HOUSE_NO_V1', 'MOBILE_NO', 'Unnamed: 18', 'Unnamed: 19', 'Unqiue',
       'length_address', 'length_name', 'family group'],
      dtype='object')