In [1]:
!pip install pandas

!pip install lxml


#only for requirements

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.6)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (4.9.1)

In [2]:
import pandas as pd

##############
scraper=pd.read_html('https://dopt.gov.in/posting-of-ias-officers-list')
print(scraper)

[                        Name         DOB             Cadre  \
0                ADITYA NEGI  26/05/1986  Himachal Pradesh
1         Aditya Kumar Anand  10/05/1986         Jharkhand
2         ADWAIT KUMAR SINGH  07/10/1988         Telangana
3                 AJAY KUMAR  26/10/1983           Haryana
4               AJEET VASANT  20/01/1987       Chhatisgarh
..                       ...         ...               ...
156         VISHESH SARANGAL  19/12/1984            Punjab
157             VINEET KUMAR  13/10/1984       Uttaranchal
158           YOGENDRA SINGH  10/04/1987             Bihar
159  YOGESH BABANRAO NIRGUDE  04/02/1984           Gujarat
160            ZEESHAN QAMER  04/12/1980         Jharkhand

                     Address                             Email Address  \
0    23/7-06(D), CWG Village             aditya[dot]negi[at]nic[dot]in
1         A-607, Curzon Road   adityak[dot]anand[at]ias[dot]nic[dot]in
2                        NaN           adwaitk[dot]singh[at]nic[dot]in
3         F-509, Curzon Road       ajay[dot]kr83[at]ias[dot]nic[dot]in
4         A-407, Curzon Road            ajeet[dot]vasant[at]nic[dot]in
..                       ...                                       ...
156       F-808, Curzon Road        vishesh[dot]sarangal[at]nic[dot]in
157  23/8-01(B), CWG Village  vineet[dot]kumar13[at]ias[dot]nic[dot]in
158  23/2-06(B), CWG Village          singh[dot]yogendra[at]nic[dot]in
159  23/6-01(B), CWG Village               y[dot]nirgude[at]nic[dot]in
160                      NaN           zeeshan[dot]qamer[at]nic[dot]in

                        Ministry/ Dept. Alloted       Desk  Photo
0    M/o Skill Development and Entrepreneurship        NaN    NaN
1                                   M/o Tourism        NaN    NaN
2      M/o Drinking Water Supply and Sanitation        NaN    NaN
3                     M/o Labour and Employment        NaN    NaN
4              M/o Information and Broadcasting        NaN    NaN
..                                          ...        ...    ...
156    M/o Drinking Water Supply and Sanitation        NaN    NaN
157                     D/o Disaster Management         DM    NaN
158                                M/o Shipping  Sagarmala    NaN
159    M/o Drinking Water Supply and Sanitation        NaN    NaN
160               M/o Petroleum and Natural Gas        NaN    NaN

[161 rows x 8 columns]]

In [32]:

data=scraper[0]
data

,Name,DOB,Cadre,Address,Email Address,Ministry/ Dept. Alloted,Desk,Photo
0,ADITYA NEGI,26/05/1986,Himachal Pradesh,"23/7-06(D), CWG Village",aditya[dot]negi[at]nic[dot]in,M/o Skill Development and Entrepreneurship,NaN,NaN
1,Aditya Kumar Anand,10/05/1986,Jharkhand,"A-607, Curzon Road",adityak[dot]anand[at]ias[dot]nic[dot]in,M/o Tourism,NaN,NaN
2,ADWAIT KUMAR SINGH,07/10/1988,Telangana,NaN,adwaitk[dot]singh[at]nic[dot]in,M/o Drinking Water Supply and Sanitation,NaN,NaN
3,AJAY KUMAR,26/10/1983,Haryana,"F-509, Curzon Road",ajay[dot]kr83[at]ias[dot]nic[dot]in,M/o Labour and Employment,NaN,NaN
4,AJEET VASANT,20/01/1987,Chhatisgarh,"A-407, Curzon Road",ajeet[dot]vasant[at]nic[dot]in,M/o Information and Broadcasting,NaN,NaN
...,...,...,...,...,...,...,...,...
156,VISHESH SARANGAL,19/12/1984,Punjab,"F-808, Curzon Road",vishesh[dot]sarangal[at]nic[dot]in,M/o Drinking Water Supply and Sanitation,NaN,NaN
157,VINEET KUMAR,13/10/1984,Uttaranchal,"23/8-01(B), CWG Village",vineet[dot]kumar13[at]ias[dot]nic[dot]in,D/o Disaster Management,DM,NaN
158,YOGENDRA SINGH,10/04/1987,Bihar,"23/2-06(B), CWG Village",singh[dot]yogendra[at]nic[dot]in,M/o Shipping,Sagarmala,NaN
159,YOGESH BABANRAO NIRGUDE,04/02/1984,Gujarat,"23/6-01(B), CWG Village",y[dot]nirgude[at]nic[dot]in,M/o Drinking Water Supply and Sanitation,NaN,NaN
160,ZEESHAN QAMER,04/12/1980,Jharkhand,NaN,zeeshan[dot]qamer[at]nic[dot]in,M/o Petroleum and Natural Gas,NaN,NaN

In [4]:
##########  data cleaning on data cleaning section ##################
#data.to_excel('IAS_info.xlsx')

In [15]:
test

In [33]:
test=data.head()

,Name,DOB,Cadre,Address,Email Address,Ministry/ Dept. Alloted,Desk,Photo
0,ADITYA NEGI,26/05/1986,Himachal Pradesh,"23/7-06(D), CWG Village",aditya[dot]negi[at]nic[dot]in,M/o Skill Development and Entrepreneurship,NaN,NaN
1,Aditya Kumar Anand,10/05/1986,Jharkhand,"A-607, Curzon Road",adityak[dot]anand[at]ias[dot]nic[dot]in,M/o Tourism,NaN,NaN
2,ADWAIT KUMAR SINGH,07/10/1988,Telangana,NaN,adwaitk[dot]singh[at]nic[dot]in,M/o Drinking Water Supply and Sanitation,NaN,NaN
3,AJAY KUMAR,26/10/1983,Haryana,"F-509, Curzon Road",ajay[dot]kr83[at]ias[dot]nic[dot]in,M/o Labour and Employment,NaN,NaN
4,AJEET VASANT,20/01/1987,Chhatisgarh,"A-407, Curzon Road",ajeet[dot]vasant[at]nic[dot]in,M/o Information and Broadcasting,NaN,NaN

In [39]:

for t in range(len(data)):
  check=data.iloc[t,4]
  check=check.replace('[dot]','.')#
  check=check.replace('[at]','@')
  data.iloc[t,4]=check
  #print(check)

In [40]:
data

,Name,DOB,Cadre,Address,Email Address,Ministry/ Dept. Alloted,Desk,Photo
0,ADITYA NEGI,26/05/1986,Himachal Pradesh,"23/7-06(D), CWG Village",aditya.negi@nic.in,M/o Skill Development and Entrepreneurship,NaN,NaN
1,Aditya Kumar Anand,10/05/1986,Jharkhand,"A-607, Curzon Road",adityak.anand@ias.nic.in,M/o Tourism,NaN,NaN
2,ADWAIT KUMAR SINGH,07/10/1988,Telangana,NaN,adwaitk.singh@nic.in,M/o Drinking Water Supply and Sanitation,NaN,NaN
3,AJAY KUMAR,26/10/1983,Haryana,"F-509, Curzon Road",ajay.kr83@ias.nic.in,M/o Labour and Employment,NaN,NaN
4,AJEET VASANT,20/01/1987,Chhatisgarh,"A-407, Curzon Road",ajeet.vasant@nic.in,M/o Information and Broadcasting,NaN,NaN
...,...,...,...,...,...,...,...,...
156,VISHESH SARANGAL,19/12/1984,Punjab,"F-808, Curzon Road",vishesh.sarangal@nic.in,M/o Drinking Water Supply and Sanitation,NaN,NaN
157,VINEET KUMAR,13/10/1984,Uttaranchal,"23/8-01(B), CWG Village",vineet.kumar13@ias.nic.in,D/o Disaster Management,DM,NaN
158,YOGENDRA SINGH,10/04/1987,Bihar,"23/2-06(B), CWG Village",singh.yogendra@nic.in,M/o Shipping,Sagarmala,NaN
159,YOGESH BABANRAO NIRGUDE,04/02/1984,Gujarat,"23/6-01(B), CWG Village",y.nirgude@nic.in,M/o Drinking Water Supply and Sanitation,NaN,NaN
160,ZEESHAN QAMER,04/12/1980,Jharkhand,NaN,zeeshan.qamer@nic.in,M/o Petroleum and Natural Gas,NaN,NaN

In [41]:
data.to_excel('IAS_info.xlsx')